spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/math_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

hostname: 31.134.176.179

server:
  error:
    include-message: always
#  port: 8081

jwt:
  token:
    secret: jwtappdemo
    expired: 3600000


plugin:
  native:
    path: "./src/main/java/com/mathsystem/domain/plugin/nativerealization"
  path: "/home/dmitry/IdeaProjects/math-system/plugins/"
  test.path: "/home/dmitry/IdeaProjects/math-system/graph.txt"

