package com.mathsystem.exceptions;

public enum ErrorCode {
    USER_ALREADY_EXIST,
    USER_NOT_FOUND,

    PLUGIN_ALREADY_EXIST,
    PLUGIN_NOT_FOUND,
    PLUGIN_JAR_ALREADY_EXIST,
    PLUGIN_JAR_NOT_FOUND,
    PLUGIN_TIME_LIMIT,
    PLUGIN_CLASS_NOT_FOUND,
    PLUGIN_INTERNAL_ERROR,

    TASK_NOT_FOUND,


    NOT_ENOUGH_RIGHT;
}
